---
title: "Oct-9-2024"
format: html
editor: visual
---

```{r}
rm(list=ls())
library(here)
library(tidyverse)
```

read tomato:

```{r}
tomato<-read.csv(here("data","tomato_data.csv"))
```

Get rows 3,7,9

```{r}
tomato|>slice(c(3,7,9))|> View()
```

all plants with fertilizer treatment and avg wt \>=145:

```{r}
tomato|>filter(Treatment=="fertilizer"&Avg_tomato_weight_g>=145)
```

save changes to a new file

```{r}
dir.create(here("outputs"))
```

now save the file

```{r}
write.csv(tomato,here("outputs","fixedtomatoes.csv"),row.names = F)#row.names=F prevents R from adding the X column
```

```{r}
toms2<-read.csv(here("outputs","fixedtomatoes.csv"))
```

Next activity

```{r}
lead<-read.csv(here("data","NoCoLead.csv"))
```

what if we want to know the average number of tests given?

```{r}
lead |>summarize(
  mean_num_tests=mean(num_tests)
)|>View()
```

Now, what is the mean number of tests per year?

```{r}
lead_summary<-lead|>
  group_by(Year)|>
  summarise(
    mean_tests_per_year=mean(num_tests)
  )
```
